apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q2vwu5fd8-python 
  janus-idp.io/tekton: q2vwu5fd8-python
  backstage.io/kubernetes-id: q2vwu5fd8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q2vwu5fd8-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  